apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakpaas-welcome
  labels:
    app: welcome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
      - name: welcome
        image: sakpaas/welcome:release-1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80