apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  assetlinks.json: |-
    [{
      "relation": ["delegate_permission/common.handle_all_urls"],
      "target": {
        "namespace": "android_app",
        "package_name": "org.happyhamster.happyhamster",
        "sha256_cert_fingerprints":
        ["8A:45:C5:AA:E9:A7:39:5B:C8:92:53:5A:90:27:86:6D:8E:8A:FC:DB:53:A9:FF:00:A0:3F:95:B9:80:4C:93:BA"]
      }
    }]
