apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakpaas-frontend
  labels:
    app: frontend
    base: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sakpaas/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: frontend-config
          mountPath: /usr/share/nginx/html/.well-known/assetlinks.json
          subPath: assetlinks.json
          readOnly: true
      volumes:
        - name: frontend-config
          configMap:
            name: frontend-config