apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-development-config
data:
  map-directive.conf: |-
    # https://serverfault.com/a/516382
    map $http_x_forwarded_proto $forward_scheme {
      default $scheme;
      https https;
    }

  frontend-development.conf: |-
    # frontend development
    server {
      # HTTP on port 80
      listen       80;
      server_name  dev.happyhamster.org;

      # This location references every path
      location / {
        proxy_pass          http://frontend-dev-service;
        proxy_http_version  1.1;
        proxy_cache_bypass  $http_upgrade;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $forward_scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
      }
    }

  frontend-integration.conf: |-
    # frontend integration
    server {
      # HTTP on port 80
      listen       80;
      server_name  int.happyhamster.org;

      # This location references every path
      location / {
        proxy_pass          http://frontend-integration-service;
        proxy_http_version  1.1;
        proxy_cache_bypass  $http_upgrade;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $forward_scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
      }
    }

  backend-development.conf: |-
    # backend development
    server {
      # HTTP on port 80
      listen       80;
      server_name  api.dev.happyhamster.org;

      # This location references every path
      location / {
        proxy_pass          http://backend-dev-service;
        proxy_http_version  1.1;
        proxy_cache_bypass  $http_upgrade;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $forward_scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
      }
    }

  backend-integration.conf: |-
    # backend integration
    server {
      # HTTP on port 80
      listen       80;
      server_name  api.int.happyhamster.org;

      # This location references all paths with the api prefix
      location /api/ {
        proxy_pass          http://backend-integration/;
        proxy_http_version  1.1;
        proxy_cache_bypass  $http_upgrade;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $forward_scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
      }

      # This location references every path
      location / {
        proxy_pass          http://backend-integration-support;
        proxy_http_version  1.1;
        proxy_cache_bypass  $http_upgrade;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $forward_scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
      }
    }

  grafana.conf: |-
    # grafana
    server {
      # HTTP on port 80
      listen       80;
      server_name  stats.happyhamster.org;

      # This location references every path
      location / {
        proxy_pass          http://grafana-service;
        proxy_http_version  1.1;
        proxy_cache_bypass  $http_upgrade;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $forward_scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
      }
    }

  keycloak.conf: |-
    # keycloak
    server {
      # HTTP on port 80
      listen       80;
      server_name  auth.happyhamster.org;

      # This location references every path
      location / {
        proxy_pass          https://keycloak-service;
        proxy_ssl_verify    off;

        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  443;
      }
    }

  documentation.conf: |-
    # keycloak
    server {
      # HTTP on port 80
      listen       80;
      server_name  docs.happyhamster.org;

      # This location references every path
      location / {
        # Redirect http to https if the connection was made with http at the proxy level
        # https://serverfault.com/a/767930
        if ($http_x_forwarded_proto = "http") {
            return 301 https://$host$request_uri;
        }

        proxy_pass          http://documentation-service;
        proxy_http_version  1.1;
        proxy_cache_bypass  $http_upgrade;

        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $forward_scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
      }
    }
