apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-development-development
  labels:
    app: proxy-development
    base: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-development
  template:
    metadata:
      labels:
        app: proxy-development
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              readOnly: true
              name: proxy-development-config
      volumes:
        - name: proxy-development-config
          configMap:
            name: proxy-development-config
