apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sakpaas-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: sakpaas-ip
    networking.gke.io/managed-certificates: "frontend-certificate-robspot,backend-certificate-robspot"
spec:
  rules:
  - host: dev.robspot.de
    http:
      paths:
      - backend:
          serviceName: backend-api
          servicePort: 8080
  - host: happyhamster.robspot.de
    http:
      paths:
      - backend:
          serviceName: frontend-service
          servicePort: 80