apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sakpaas-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: sakpaas-ip
    networking.gke.io/managed-certificates: "frontend-certificate,backend-certificate,welcome-certificate,backend-development-certificate,frontend-dev-certificate,frontend-www-certificate,frontend-integration-certificate,backend-integration-certificate,keycloak-certificate,documentation-certificate"
spec:
  backend:
    serviceName: frontend-service
    servicePort: 80
  rules:
  - host: happyhamster.org
    http:
      paths:
      - backend:
          serviceName: frontend-service
          servicePort: 80
  - host: www.happyhamster.org
    http:
      paths:
      - backend:
          serviceName: frontend-service
          servicePort: 80
  - host: api.happyhamster.org
    http:
      paths:
      - backend:
          serviceName: backend-service
          servicePort: 80
  #- host: welcome.happyhamster.org
  #  http:
  #    paths:
  #    - backend:
  #        serviceName: welcome-service
  #        servicePort: 80
  #- host: stats.happyhamster.org
  #  http:
  #    paths:
  #    - backend:
  #        serviceName: proxy-development-service
  #        servicePort: 80
  - host: dev.happyhamster.org
    http:
      paths:
      - backend:
          serviceName: proxy-development-service
          servicePort: 80
  - host: api.dev.happyhamster.org
    http:
      paths:
      - backend:
          serviceName: proxy-development-service
          servicePort: 80
  #- host: int.happyhamster.org
  #  http:
  #    paths:
  #    - backend:
  #        serviceName: proxy-development-service
  #        servicePort: 80
  #- host: api.int.happyhamster.org
  #  http:
  #    paths:
  #    - backend:
  #        serviceName: proxy-development-service
  #        servicePort: 80
  - host: auth.happyhamster.org
    http:
      paths:
      - backend:
          serviceName: proxy-development-service
          servicePort: 80
  #- host: docs.happyhamster.org
  #  http:
  #    paths:
  #    - backend:
  #        serviceName: proxy-development-service
  #        servicePort: 80
