apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nominatim
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nominatim
        track: stable
    spec:
      volumes:
      - name: nominatim-secret-volume
        secret:
          secretName: nominatim-storage-secret
      containers:
      - name: nominatim-k8s
        image: peterevans/nominatim-k8s:latest
        env:
        - name: NOMINATIM_MODE
          value: RESTORE
        - name: NOMINATIM_DATA_LABEL
          value: germany-17-04-2020
        - name: NOMINATIM_SA_KEY_PATH
          value: "/etc/nominatim-secret-volume/nominatim-sa.json"
        - name: NOMINATIM_PROJECT_ID
          value: turnkey-tribute-271722
        - name: NOMINATIM_GS_BUCKET
          value: "gs://nominatim-happyhamster"
        volumeMounts:
        - name: nominatim-secret-volume
          readOnly: true
          mountPath: /etc/nominatim-secret-volume
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /search
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1