apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakpaas-welcome
  labels:
    app: welcome
    base: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
      - name: welcome
        image: sakpaas/welcome:release-1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 20m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 10Mi
