apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakpaas-backend-integration
  labels:
    app: backend-integration
    environment: integration
    base: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-integration
      environment: integration
  template:
    metadata:
      labels:
        app: backend-integration
        environment: integration
    spec:
      containers:
      - name: backend
        image: sakpaas/backend:integration
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: spring.datasource.url
          value: jdbc:postgresql://postgres-integration:5432/postgres
        - name: spring.datasource.username
          value: postgres
        - name: spring.datasource.password
          value: test123
        - name: keycloak.auth-server-url
          value: https://auth.happyhamster.org/auth/
        - name: keycloak.realm
          value: happyhamster
        - name: keycloak.resource
          value: backend
        - name: keycloak.enabled
          value: "true"
        - name: app.search-api-url
          value: http://nominatim
        - name: keycloak.credentials.secret
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: key.txt
        readinessProbe:
          httpGet:
            port: 8080
          failureThreshold: 20
          periodSeconds: 10
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 25m
