apiVersion: v1
kind: Service
metadata:
  name: backend-integration-management
  labels:
    app: backend-integration
    environment: integration
spec:
  selector:
    app: backend-integration
  type: NodePort
  ports:
  - protocol: TCP
    port: 9000
    protocol: TCP
    targetPort: 9000
