apiVersion: v1
kind: Service
metadata:
  name: backend-integration
  labels:
    app: backend
    environment: integration
spec:
  selector:
    app: backend
    environment: integration
  type: NodePort
  ports:
    - name: backend
      protocol: TCP
      port: 80
      targetPort: 8080
