apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak
  labels:
    app: postgres-keycloak
    environment: production
spec:
  selector:
    app: postgres-keycloak
    environment: production
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
