apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakpaas-welcome-development
  labels:
    app: welcome-development
    base: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-development
  template:
    metadata:
      labels:
        app: welcome-development
    spec:
      containers:
      - name: welcome-development
        image: sakpaas/welcome:development
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 10m
