apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakpaas-welcome-development
  labels:
    app: welcome-development
    base: nginx
spec:
  # The deployment was scaled to 0, as it was not configured in the ingress.
  # But this file has to be here, as it is being used by the GitHub Action
  # of github.com/SAKPaaS/welcome
  replicas: 0
  selector:
    matchLabels:
      app: welcome-development
  template:
    metadata:
      labels:
        app: welcome-development
    spec:
      containers:
      - name: welcome-development
        image: sakpaas/welcome:development
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 10m
