apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  labels:
    app: prometheus
    environment: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
