apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  labels:
    app: prometheus
    environment: monitoring
    base: prometheus
spec:
  replicas: 1
  serviceName: prometheus
  selector:
    matchLabels:
      app: prometheus
      environment: monitoring
  template:
    metadata:
      labels:
        app: prometheus
        environment: monitoring
    spec:
      serviceAccountName: prometheus
      initContainers:
        - name: prometheus-data-permission-fix
          image: busybox
          command: ["/bin/chmod", "-R", "777", "/prometheus"]
          volumeMounts:
            - name: storage-volume
              mountPath: /prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: storage-volume
              mountPath: /prometheus
      volumes:
        - name: config-volume
          configMap:
           name: prometheus-config
        - name: storage-volume
          persistentVolumeClaim:
            claimName: prometheus
