apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cicd-cluster-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["deployments", "deployments/scale", "replicasets", "pods", "statefulsets", "statefulsets/scale"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["*"]
