apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicd-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: github-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: cicd-cluster-role
  apiGroup: rbac.authorization.k8s.io
