apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  labels:
    app: keycloak
    environment: production
spec:
  selector:
    app: keycloak
    environment: production
  ports:
  - name: https
    port: 443
    targetPort: 8443
  selector:
    app: keycloak
  type: NodePort