apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak # has to match .spec.template.metadata.labels
  serviceName: "keycloak"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: keycloak # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: keycloak
        image: jboss/keycloak
        ports:
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: h2
        ports:
        - containerPort: 8080
          name: web
        