apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf
data:
  grafana.ini: |-
    [auth]
    oauth_auto_login = true
    domain = stats.happyhamster.org
    signout_redirect_url = https://auth.happyhamster.org/auth/realms/happyhamster-internal/protocol/openid-connect/logout?redirect_uri=http://stats.happyhamster.org
    [server]
    root_url = http://stats.happyhamster.org/
    [auth.generic_oauth]
    name = HappyHamster
    enabled = true
    allow_sign_up = true
    client_id = grafana
    scopes = account
    auth_url = https://auth.happyhamster.org/auth/realms/happyhamster-internal/protocol/openid-connect/auth
    token_url = https://auth.happyhamster.org/auth/realms/happyhamster-internal/protocol/openid-connect/token
    api_url = https://auth.happyhamster.org/auth/realms/happyhamster-internal/protocol/openid-connect/userinfo
    role_attribute_path = contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-editor') && 'Editor' || 'Viewer'

  
    