apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  replicas: 0
  serviceName: "grafana"
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      initContainers:
        - name: grafana-data-permission-fix
          image: busybox
          command: ["/bin/chmod", "-R", "777", "/grafana"]
          volumeMounts:
            - name: storage-volume
              mountPath: /grafana
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - name: grafana
              containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: storage-volume
            - name: grafana-conf
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
          resources:
            limits:
              cpu: 500m
              memory: 40Mi
            requests:
              cpu: 25m
              memory: 30Mi
      volumes:
        - name: grafana-conf
          configMap:
           name: grafana-conf
        - name: storage-volume
          persistentVolumeClaim:
            claimName: grafana
