apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  replicas: 1
  serviceName: "grafana"
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      initContainers:
        - name: grafana-data-permission-fix
          image: busybox
          command: ["/bin/chmod", "-R", "777", "/grafana"]
          volumeMounts:
            - name: storage-volume
              mountPath: /grafana
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - name: grafana
              containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: storage-volume
            - mountPath: /etc/grafana/provisioning/datasources
              name: datasources-volume
              readOnly: false
      volumes:
        - name: datasources-volume
          configMap:
            defaultMode: 420
            name: grafana-datasources
        - name: storage-volume
          persistentVolumeClaim:
            claimName: grafana
