apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
    environment: management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
      environment: management
  template:
    metadata:
      labels:
        app: pgadmin
        environment: management
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@admin"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "asdajuki"
        ports:
        - containerPort: 80
