kind: Service
apiVersion: v1
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
    environment: management
spec:
  selector:
    app: pgadmin
    environment: management
  ports:
  - name: pgadmin
    protocol: TCP
    port: 80
    targetPort: 80
