apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-integration-support
  labels:
    app: backend-support
    environment: integration
data:
  config.json: |-
    {
      "rootUrl": "https://api.int.happyhamster.org/api"
    }
  assetlinks.json: |-
    [{
      "relation": ["delegate_permission/common.handle_all_urls"],
      "target": {
        "namespace": "android_app",
        "package_name": "org.happyhamster.happyhamster",
        "sha256_cert_fingerprints":["enter_fingerprint_here"]
      }
    }]
  robots.txt: |-
    User-agent: *
    Disallow: /
