apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-integration-support
  labels:
    app: backend-support
    environment: integration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
