apiVersion: v1
kind: Service
metadata:
  name: backend-integration-support
  labels:
    app: backend-support
    environment: integration
spec:
  selector:
    app: backend-support
    environment: integration
  type: NodePort
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
