apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-integration-config
  labels:
    app: frontend-integration
    environment: integration
data:
  config.json: |-
    {
      "rootUrl": "https://api.happyhamster.org"
    }
  assetlinks.json: |-
    [{
      "relation": ["delegate_permission/common.handle_all_urls"],
      "target": {
        "namespace": "android_app",
        "package_name": "org.happyhamster.happyhamster",
        "sha256_cert_fingerprints":["enter_fingerprint_here"]
      }
    }]
  robots.txt: |-
    User-agent: *
    Disallow: /
