apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-integration
  labels:
    app: frontend
    environment: integration
    base: nginx
spec:
  replicas: 0
  selector:
    matchLabels:
      app: frontend
      environment: integration
  template:
    metadata:
      labels:
        app: frontend
        environment: integration
        base: nginx
    spec:
      containers:
        - name: frontend
          image: sakpaas/frontend:integration
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 10m
              memory: 10Mi
            requests:
              cpu: 5m
              memory: 5Mi
          volumeMounts:
            - name: frontend-integration
              mountPath: /usr/share/nginx/html/config/config.json
              subPath: config.json
              readOnly: true
            - name: frontend-integration
              mountPath: /usr/share/nginx/html/.well-known/assetlinks.json
              subPath: assetlinks.json
              readOnly: true
            - name: frontend-integration
              mountPath: /usr/share/nginx/html/robots.txt
              subPath: robots.txt
              readOnly: true
      volumes:
        - name: frontend-integration
          configMap:
            name: frontend-integration
