apiVersion: v1
kind: Service
metadata:
  name: frontend-integration
  labels:
    app: frontend
    environment: integration
spec:
  selector:
      app: frontend
      environment: integration
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
