apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakpaas-backend
  labels:
    app: backend
    base: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9000'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
      - name: backend
        image: sakpaas/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: spring.datasource.url
          value: jdbc:postgresql://10.60.6.56:5432/postgres
        - name: spring.datasource.username
          value: postgres
        - name: spring.datasource.password
          value: test123
        - name: keycloak.auth-server-url
          value: https://auth.happyhamster.org/auth/
        - name: keycloak.realm
          value: happyhamster
        - name: keycloak.resource
          value: backend
        - name: keycloak.enabled
          value: "true"
        - name: app.search-api-url
          value: http://nominatim
        - name: keycloak.credentials.secret
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: key.txt
        readinessProbe:
          httpGet:
            port: 8080
          failureThreshold: 20
          periodSeconds: 10
