apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation-deployment
  labels:
    app: documentation
    environment: production
    base: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentation
      environment: production
  template:
    metadata:
      labels:
        app: documentation
        environment: production
    spec:
      containers:
        - name: swagger
          image: sakpaas/documentation:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 100Mi
