apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-development-config
data:
  config.json: |-
    {
      "rootUrl": "https://api.dev.happyhamster.org"
    }
  assetlinks.json: |-
    [{
      "relation": ["delegate_permission/common.handle_all_urls"],
      "target": {
        "namespace": "android_app",
        "package_name": "org.happyhamster.happyhamster",
        "sha256_cert_fingerprints":["enter_fingerprint_here"]
      }
    }]