apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakpaas-frontend-development
  labels:
    app: frontend-development
    base: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-development
  template:
    metadata:
      labels:
        app: frontend-development
    spec:
      containers:
      - name: frontend
        image: sakpaas/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
