apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakpaas-frontend-development
  labels:
    app: frontend-development
    base: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-development
  template:
    metadata:
      labels:
        app: frontend-development
    spec:
      containers:
      - name: frontend
        image: sakpaas/frontend:development
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
            limits:
              cpu: 10m
              memory: 10Mi
            requests:
              cpu: 5m
              memory: 5Mi
        volumeMounts:
          - name: frontend-development-config
            mountPath: /usr/share/nginx/html/config/config.json
            subPath: config.json
            readOnly: true
          - name: frontend-development-config
            mountPath: /usr/share/nginx/html/.well-known/assetlinks.json
            subPath: assetlinks.json
            readOnly: true
          - name: frontend-development-config
            mountPath: /usr/share/nginx/html/robots.txt
            subPath: robots.txt
            readOnly: true
      volumes:
        - name: frontend-development-config
          configMap:
            name: frontend-development-config
