apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakpaas-frontend-development
  labels:
    app: frontend-development
    base: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-development
  template:
    metadata:
      labels:
        app: frontend-development
    spec:
      containers:
      - name: frontend
        image: sakpaas/frontend:development
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
            - mountPath: /usr/share/nginx/html/config/
              readOnly: true
              name: frontend-config
      volumes:
        - name: frontend-config
          configMap:
            name: frontend-config

