apiVersion: v1
kind: Service
metadata:
  name: frontend-dev-service
spec:
  selector:
    app: frontend-development
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    protocol: TCP
    targetPort: 80
